### PR TITLE
Function Annotations

### PR DESCRIPTION
**Pull request by tuomas56**
I have found function annotations to be very useful in Python and so decided to implement them in Rapydscript. This will also potentially help when porting Python modules over to Rapydscript, as annotations will no longer have to be removed.
 
They behave almost exactly as specified in [PEP3107](https://www.python.org/dev/peps/pep-3107/).
Both argument and return annotations can be added like this:
```python
def func(a: int, b: str) -> float:
    pass
```
The annotations are placed into a dict (a JS object here, not a full dict) with the return annotation (if it exists) having the key 'return', and argument keying as themselves.T he function object's `__annotations__` attribute is then set to this. E.g:

```python
func.__annotations__ == {'a': int, 'b': str, 'return': float}
```

However, the current implementation has some caveats:

* The `__annotations__` property will only be set on named functions.
* Annotations can not be used on functions which are being used as an expression, not a statement.

For example:

```python
print(def func():
    pass
)
```

Would not work. I have yet to find a way to make this work - I have tried wrapping the whole thing in a self-invoking function but that prevented named functions from being defined in the right scope and has some issues with binding and `this`.) Also this:

```python
def(x: int):
    pass
```

Would not set the `__annotations__` attribute, for the same reasons.

My pull request also seems to contain some additions to `baselib-plain-{pretty, ugly}.js` which is odd as I definitely did not make this changes. I'm not sure whether these were autogenerated or from your main fork.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Cool, I agree annotations can be useful.

However, I am just about to make some changes to the compiler that should make it possible to add function annotations even to function expressions and anonymous functions. If my approach works then you can make your code more general. So I suggest waiting a day or so (I plan on making the changes today). 

Some meta comments:

1) The baselib*.js files are generated by the compiler. Therefore, if you make changes that change the compiler's output, those will likely to be changed as well. 

2) Please add some tests. Although historically RapydScript has had very few tests. My policy since forking rapydscript-ng is to have tests for new features.

**Comment by kovidgoyal** [comment]
I'm done with the changes to allow annotations for arbitrary functions. Now you can simply hook into function_annotations() to add func.__annotations__ to all functions, regardless of whether they are anonymous, expressions or statements.

I suggest you rebase your branch on top of upstream/master to avoid the merge commits in the pull request. Let me know when you are ready to have this PR reviewed.

**Comment by kovidgoyal** [comment]
FYI, I just committed some changes to the rs-ng build system so that the built compiler files are no longer tracked in source control. This should make pull requests much easier, with fewer conflicts. So just start over and put in your changes to the .pyj files and run ./build

That should give you a clean pull request including only changes to *.pyj files not generated *.js files.

See HACKING.md for details.

**Comment by tuomas56** [comment]
I think this is ready.
(Despite rebasing as suggested, there seem to be several merge commits in the PR?)

**Comment by kovidgoyal** [comment]
I'll take care of the merge commits when I merge it myself -- I can merge into a branch, rebase and then merge into master. I'll review the code soon.

**Comment by kovidgoyal** [comment]
Just occurred to me that if I do what I suggested about rebasing myself, you will lose the credits in github in terms of having contributed to rapydscript-ng (although I will add you to the CONTRIBUTORS file). However, if you want to preserve your github credits as well, you can do the following:

1) Close this pull request
2) Take a diff of only changed *.pyj files in your branch compared to upstream/master and save it somewhere.
3) Do git reset --hard upstream/master && git push -f
4) Apply the previously saved patch
5) Make a new pull request

If that is too much bother, then I will take care of doing it myself and just add you to CONTRIBUTORS. Let me know.

**Comment by tuomas56** [comment]
To be honest, I don't mind, just go ahead with your original idea.

**Comment by kovidgoyal** [comment]
OK, what name do you want in the CONTRIBUTORS file? Your github alias?

**Comment by tuomas56** [comment]
Tuomas Laakkonen would be good, thanks.

**Comment by atsepkov** [comment]
Hi guys, stumbled upon this commit while integrating some of Kovid's other fixes into original RapydScript. Type annotations is something I was thinking about adding for a while but was lazy about , thank you for tackling this. I have merged the changes in and given credit to Tuomas in the original fork as well: https://github.com/atsepkov/RapydScript/commit/eff67d9be901502ae27034fc2f0f8868e351c7d9

**Pull request closed without merging**
